// SELECT THEME
export const CHANGE_THEME = 'CHANGE_THEME';

// SELECT VIEW TYPE
export const SELECT_THUMBS_VIEW = 'SELECT_THUMBS_VIEW';
export const SELECT_DETAIL_VIEW = 'SELECT_DETAIL_VIEW';

// FILES ACTIONS
export const DELETE_FILE = 'DELETE_FILE';
export const SELECT_FILE = 'SELECT_FILE';
export const DELETE_SELECTED_FILES = 'DELETE_SELECTED_FILES';

// LOADING
export const FINISH_APP_LOADING = 'FINISH_APP_LOADING';